# Generated by Django 3.0.4 on 2020-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patiens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('birthdate', models.TextField()),
                ('gender', models.TextField()),
                ('blood_type', models.TextField()),
            ],
            options={
                'db_table': 'app_server.api.patients',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
