# Generated by Django 3.0.4 on 2020-05-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200516_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patiens',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patiens',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patiens',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patiens',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
    ]
