# Generated by Django 3.0.4 on 2020-05-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200516_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patiens',
            new_name='Patients',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
