# Generated by Django 3.0.4 on 2020-05-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200517_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='birth_date',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='blood_type',
            new_name='bloodType',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='lastname',
            new_name='lastlame',
        ),
    ]
