# Generated by Django 3.0.4 on 2020-05-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200530_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='lastlame',
            new_name='lastname',
        ),
    ]
