# Generated by Django 3.0.4 on 2020-07-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200710_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BloodType'),
        ),
    ]
