# Generated by Django 3.0.4 on 2020-07-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200712_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bloodType',
            new_name='bloodtype',
        ),
    ]
