# Generated by Django 3.0.4 on 2020-07-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200713_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodtype',
            old_name='type',
            new_name='label',
        ),
        migrations.AddField(
            model_name='bloodtype',
            name='value',
            field=models.CharField(choices=[('A+', 'A+ Blood Type'), ('A-', 'A- Blood Type'), ('B+', 'B+ Blood Type'), ('B-', 'B- Blood Type'), ('AB+', 'AB+ Blood Type'), ('AB-', 'AB- Blood Type'), ('0+', '0+ Blood Type'), ('0-', '0- Blood Type')], default='tmp', max_length=10),
            preserve_default=False,
        ),
    ]
