# Generated by Django 3.0.4 on 2020-11-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200713_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('test', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'api_patients',
            },
        ),
        migrations.AlterModelTable(
            name='bloodtype',
            table='api_bloodtype',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='patients',
            name='bloodtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BloodType'),
        ),
    ]
