# Generated by Django 3.0.4 on 2020-11-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_patients_fk_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='test',
        ),
    ]
