# Generated by Django 3.0.4 on 2020-11-22 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20201122_2130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloodtype',
            table='api_bloodtype',
        ),
    ]
