# Generated by Django 3.2 on 2021-08-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_auto_20200516_1712'), ('api', '0003_auto_20200516_1724')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patiens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('birthdate', models.TextField()),
                ('gender', models.TextField()),
                ('blood_type', models.TextField()),
            ],
            options={
                'db_table': 'app_server.api.patients',
            },
        ),
    ]
