# Generated by Django 3.0.4 on 2020-05-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200516_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patiens',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patiens',
            name='password',
        ),
    ]
