# Generated by Django 3.0.4 on 2020-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200710_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtype',
            name='bloodType',
            field=models.CharField(max_length=3),
        ),
    ]
