# Generated by Django 3.0.4 on 2020-07-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200713_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodtype',
            old_name='bloodType',
            new_name='type',
        ),
    ]
