# Generated by Django 3.0.4 on 2020-11-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201112_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='test',
        ),
    ]
