# Generated by Django 3.0.4 on 2020-11-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_patients_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='test',
            field=models.CharField(default='', max_length=50),
        ),
    ]
