# Generated by Django 3.0.4 on 2020-11-14 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_patients_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='fk_user_id',
            new_name='fk_user',
        ),
    ]
