# Generated by Django 3.0.4 on 2020-11-18 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20201114_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='bloodtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BloodType'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
