# Generated by Django 3.0.4 on 2020-11-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20201118_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtype',
            name='value',
        ),
    ]
