# Generated by Django 3.0.4 on 2020-11-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20201122_1917'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bloodtype',
            table='api_bloodType',
        ),
    ]
