# Generated by Django 3.2 on 2021-08-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210802_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='bloodType',
            new_name='blood_type',
        ),
    ]
